
# html lang
language: zh-CN
keywords: hexo theme

# main menu navigation
menu:
  home: /
  # sites: /sites/
  demo: https://jeff_zhong.gitee.io/demo/
  # archives: /archives
  # categories: /categories
  # tags: /tags
  search: javascript:;
  # commonweal: /404.html
  # about: /about

menu_icon:
  home: icon-home
  sites: icon-book
  demo: icon-page
  archives: icon-file-text
  categories: icon-book
  tags: icon-tags
  search: icon-search
  about: icon-user

state:
  posts: /archives
  categories: /categories
  tags: /tags

social:
  github: https://github.com/edwardzhong
  x: https://x.com/jeff_zhong3
  facebook: https://www.facebook.com/jianfeng.edward
  weibo: http://weibo.com/1593251850
  # google-plus: /
  # qq: /
  # weixin: /
  rss: /atom.xml

social_icon:
  github: icon-github
  twitter: icon-twitter
  facebook: icon-facebook
  weibo: icon-weibo
  google+: icon-gplus
  google-plus: icon-gplus
  qq: icon-qq
  weixin: icon-wechat
  wechat: icon-wechat
  rss: icon-rss

# Miscelaneous
favicon: /favicon.ico

# stylesheets loaded in the <head>
stylesheets:
  - /lib/fontello/fontello.css
  - /lib/reboto/roboto.css
  - /css/index.css

# scripts loaded in the end of the body
scripts:
  - /lib/jquery-2.2.3.min.js
  - /lib/qrcode.min.js
  - /js/index.js
